name: Deploy Live Production
on:
  push:
    branches: [ main ]

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write   # 👈 required for Firebase action to create check runs
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # temporary override

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.18.0

      - name: Deploy to Live Site
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN_PROD }}'
          projectId: my-devops-portfolio-prod
          channelId: live